/**
 * Constants for the action types
 */

export const FETCH_SECTION_LAYOUT = 'FETCH_SECTION_LAYOUT';
export const FETCH_SECTION_EDIT_LAYOUT = 'FETCH_SECTION_EDIT_LAYOUT';
export const UPDATE_LAYOUT_SETTINGS = 'UPDATE_LAYOUT_SETTINGS';
export const ADD_SECTION = 'ADD_SECTION';


/**
 * Allergy Action Types
 */

export const FETCH_PATIENT_ALLERGIES = 'FETCH_PATIENT_ALLERGIES';

/**
 * Medication Action Types
 */
export const FETCH_PATIENT_MEDICATIONS = 'FETCH_PATIENT_MEDICATIONS';
export const DELETE_PATIENT_MEDICATION = 'DELETE_PATIENT_MEDICATION';