/**
 * Constants for the action types
 */

export const FETCH_SECTION_LAYOUT = 'FETCH_SECTION_LAYOUT';
export const FETCH_SECTION_EDIT_LAYOUT = 'FETCH_SECTION_EDIT_LAYOUT';
export const UPDATE_LAYOUT_SETTINGS = 'UPDATE_LAYOUT_SETTINGS';
export const ADD_SECTION = 'ADD_SECTION';